### ISSUE TITLE
CV manquant

### ISSUE THREAD

**Issue by SirHautDeFraise** [Mschapxb/monCv#1]
Il est où ?

**Comment by Neguro** [comment]
Ouais il est où le cv ?

**Comment by SirHautDeFraise** [comment]
J'aimerais pouvoir le visionner demain c'est énervant.
Bien Cordialement,
Moi-même

**Comment by SirHautDeFraise** [comment]
Merci j'ai pu le voir dans la branche.
Faut apprendre à utiliser GitHub
Bonne soirée.

**Comment by Mschapxb** [comment]
c'est fait.
